---
- name: GET FACTS FROM FORTIMANAGER
  hosts: fortimanager
  connection: local
  gather_facts: false

  tasks:
    - name: GET FORTIMANAGER FACTS AND FORTIGATES AND CONFIGS
      fortimgr_facts:
        provider: "{{ fortimanager_provider }}"
        fortigates: "all"
        config_filter: "all"